import Head from "next/head";

import ConnectedAddress from "../components/ConnectedAddress";
import ConnectWallet from "../components/ConnectWallet";
import MembershipNFT from "../components/MembershipNFT";
import MainTitle from "../components/MainTitle";
import { useWeb3 } from "@3rdweb/hooks";
import Dashboard from "../components/Dashboard";
import { useEffect, useState } from "react";
import { ThirdwebSDK } from "@3rdweb/sdk";

const sdk = new ThirdwebSDK("rinkeby");

const bundleDropModule = sdk.getBundleDropModule(
  "0xF8E4dC17FC89cEA8A70ba42Ed1301586e0052Abb"
);

export default function Home() {
  const { address } = useWeb3();
  const [hasClaimedNFT, setHasClaimedNFT] = useState(false);

  useEffect(() => {
    if (!address) {
      return;
    }

    bundleDropModule
      .balanceOf(address, "0")
      .then((balance) => {
        if (balance.gt(0)) {
          setHasClaimedNFT(true);
          console.log("🌟 this user has a membership NFT!");
        }
      })
      .catch((error) => {
        console.error("failed to get nft balance", error);
      });
  }, [address]);

  return (
    <div className="bg-got bg-no-repeat bg-cover bg-[top_left] 2xl:bg-[top_left_-150px]">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="preload"
          href="/fonts/TrajanPro/TrajanPro-Regular.ttf"
          as="font"
          crossOrigin=""
        />
        <link
          rel="preload"
          href="/fonts/TrajanPro/TrajanPro-Bold.ttf"
          as="font"
          crossOrigin=""
        />
      </Head>

      <main className={"w-full h-[100vh] items-center grid lg:grid-cols-12"}>
        <div className="col-span-5" />
        <div className="col-span-6 flex flex-col items-center gap-[70px] ">
          <MainTitle />
          {!address && <ConnectWallet />}
          {!hasClaimedNFT && address && <MembershipNFT />}
          {hasClaimedNFT && address && <Dashboard />}
        </div>
      </main>

      {/* <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer> */}
    </div>
  );
}
